#!/bin/bash

# Copyright © 2026 Pittsburgh Supercomputing Center.
# All Rights Reserved.

VERSION=0.40
PACKAGE=trimmomatic
DIRECTORY=$(dirname $0)

if [ -f /shared/containers/loader ]; then
  source /shared/containers/loader
fi

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif java -jar /opt/trimmomatic/trimmomatic-0.40.jar "$@"
